### ISSUE TITLE
在 2 to 3 后出现 /usr/local/lib/python3.4/site-packages/tgrocery/learner/util.so.1

### ISSUE THREAD

**Issue by iQuick** [2shou/TextGrocery#12]
在 2 to 3 后出现 /usr/local/lib/python3.4/site-packages/tgrocery/learner/util.so.1

这个是错误怎么解决呢？

**Comment by 2shou** [comment]
暂时还不支持Python3，请换用2.7再尝试

**Comment by 2shou** [comment]
或者你把2to3之后的源码PR一份给我？

**Comment by iQuick** [comment]
util.so.1 的问题已经解决了，是没有 gcc 的原因，导致没有编译出 .so 文件，不过现在报另外个错误 

`>>> from tgrocery import Grocery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/tgrocery/__init__.py", line 2, in <module>
    from .classifier import *
  File "/usr/local/lib/python3.4/site-packages/tgrocery/classifier.py", line 6, in <module>
    from .learner import *
  File "/usr/local/lib/python3.4/site-packages/tgrocery/learner/__init__.py", line 1, in <module>
    from .learner import *
  File "/usr/local/lib/python3.4/site-packages/tgrocery/learner/learner.py", line 48, in <module>
    class SVMProblem(Structure):
  File "/usr/local/lib/python3.4/site-packages/tgrocery/learner/learner.py", line 50, in SVMProblem
    _types = [liblinear.problem, POINTER(liblinear.feature_node), c_int64]
AttributeError: 'module' object has no attribute 'problem'`

**Comment by iQuick** [comment]
2 to 3 的代码是使用 PrashntS 的 https://github.com/PrashntS/TextGrocery

**Comment by jammy112** [comment]
我也出现了动态加载库的问题，windows环境下的   
   from .learner import *
  File "C:\Users\xiaoj\workspace_luna\PythonLearn1\src\tgrocery\learner\learner.
py", line 21, in <module>
    util = CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'util.d
ll'))
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]

**Comment by huahuizi** [comment]
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\baiwan\TextGrocery\index.py", line 8, in <module>
    from tgrocery import Grocery
  File "C:\Python27\lib\site-packages\tgrocery\__init__.py", line 2, in <module>
    from classifier import *
  File "C:\Python27\lib\site-packages\tgrocery\classifier.py", line 6, in <module>
    from .learner import *
  File "C:\Python27\lib\site-packages\tgrocery\learner\__init__.py", line 1, in <module>
    from .learner import *
  File "C:\Python27\lib\site-packages\tgrocery\learner\learner.py", line 21, in <module>
    util = CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'util.so.1'))
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] 

我也出现这个问题了，怎么解决呢windows7

**Comment by mickelfeng** [comment]
windows下还不支持

**Comment by ye6hao** [comment]
Traceback (most recent call last):
  File "/Users/ye6hao/Documents/workspace/TextGrocery/TextGrocery-master/runtests.py", line 7, in <module>
    from tgrocery import Grocery
  File "/Users/ye6hao/Documents/workspace/TextGrocery/TextGrocery-master/tgrocery/__init__.py", line 2, in <module>
    from classifier import *
  File "/Users/ye6hao/Documents/workspace/TextGrocery/TextGrocery-master/tgrocery/classifier.py", line 6, in <module>
    from .learner import *
  File "/Users/ye6hao/Documents/workspace/TextGrocery/TextGrocery-master/tgrocery/learner/__init__.py", line 1, in <module>
    from .learner import *
  File "/Users/ye6hao/Documents/workspace/TextGrocery/TextGrocery-master/tgrocery/learner/learner.py", line 21, in <module>
    util = CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'util.so.1'))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/ye6hao/Documents/workspace/TextGrocery/TextGrocery-master/tgrocery/learner/util.so.1, 6): image not found
-----------------------------------
2.7下运行的。找不到解决的方法了。。求助😢

**Comment by cosmichut** [comment]
我修订了基于2shou的 PrashntS 的版本（for python3），现在可以支持python3 和  windows平台了。。详情见：
https://github.com/cosmichut/TextGrocery

**Comment by oliverxing95** [comment]
> 在 2 to 3 后出现 /usr/local/lib/python3.4/site-packages/tgrocery/learner/util.so.1
> 
> 这个是错误怎么解决呢？

hi 同样遇到了这个问题，请问是如何解决的呢？
