### ISSUE TITLE
从文件读取时总是失败

### ISSUE THREAD

**Issue by Sinchuck** [2shou/TextGrocery#20]
我从文件中读取数据训练时一直失败
```
optimization finished, #iter = 1
Objective value = 0.000000
nSV = 0
True
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.229 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "/home/sinchuck/PythonPratice/sougou_result.py", line 15, in <module>
    predict_result = grocery.predict('纹身 图片 编程 软件 古风 模具 官网 螺距 螺纹 酒吧 表情 男生 数控技术 客服 切削液 价格表 分界线 钻石 喊麦 霸气')
  File "/usr/local/lib/python2.7/dist-packages/tgrocery/__init__.py", line 43, in predict
    return self.model.predict_text(single_text)
  File "/usr/local/lib/python2.7/dist-packages/tgrocery/classifier.py", line 57, in predict_text
    y = self.text_converter.get_class_name(int(y))
  File "/usr/local/lib/python2.7/dist-packages/tgrocery/converter.py", line 140, in get_class_name
    return self.class_map.to_class_name(class_idx)
  File "/usr/local/lib/python2.7/dist-packages/tgrocery/converter.py", line 114, in to_class_name
    'class idx ({0}) should be less than the number of classes ({0}).'.format(idx, len(self.idx2class)))
KeyError: 'class idx (34190240) should be less than the number of classes (34190240).'
```
这是程序源码:
```
#!/usr/bin/env python
# encoding: utf-8

from tgrocery import Grocery

grocery = Grocery('sougou')
train_src = '/home/sinchuck/sougou/age.txt'
grocery.train(train_src)
print grocery.get_load_status()

predict_result = grocery.predict('纹身 图片 编程 软件 古风 模具 官网 螺距 螺纹 酒吧 表情 男生 数控技术 客服 切削液 价格表 分界线 钻石 喊麦 霸气')
print predict_result
```
age.txt文件如下:
```
1		长官 双沟 教师节 柔和 图片 农场 诗句 价格表 行李 小说 蒜苔 征文 表情 家常 根号 发票 星座 百度 天才 魔棒
4		剖腹产 奶粉 喜宝 属鸡 小儿 肚子 属猪 刀口 芦花 价格表 心脏病 功效 线头 声音 儿歌 眼睫毛 湿疹 胶囊 肠胃 先天性
1		小说 书包 全文 养女 软化 成妃 师徒 涟漪 歌曲 媚媚 肉文 进化史 销魂 温柔 伟大 爸爸 幸福 冥界 头发 弄潮
6		发票 汽车 购车 新车 进口车 有限公司 个人 增值税 专用发票 区别 公证书 权益法 消费者 原车 倾尘 赔偿标准 汽车贸易 个人信息 上户 结果
3		编码器 拉链 脉冲雷达 电影 孤舰 处理器 丧尸 口碑 市长 国度 文件 皇帝 暴风 系统 编码 发动机 抗体 封闭抗体 间谍活动 科委
2		苹果 百度 高手 鸡腿 校园 老版 炖法 缠绵 剧情 链接 语音 资源 技巧 学姐 电影 记录 墙式 图片 完整版 版聊
3		软肋 铠甲 待人 国品 浏览器 游戏 纯金 信用社 坚果 美食 分队 百度 金牌 视频 眉毛 节目 酒店 反光膜 电玩 年轻
3		十字绣 农村 服务站 官网 汽车 罚款 成人 前途 学校 流行歌曲 飞云 前景 行业 厨师 时间段 美容 传奇 装饰 对话框 售票点
3		运程 股票 线图 黑衣人 投弹手 图片 意思 生肖 米粒 太极拳 虱子 熊市 煤矿 天空 官网 技付 能市 神符 演员表 侧神
1		百度 废材 逆天 拳皇 魔盗 武神 风云 人类 妖孽 风暴 机甲 星河 仙侠 酒神 重生 原形 电影 帝国 飞天 女友

```
请问这是什么原因?(备注,同样的代码,只要把train_src改成list类型就可以运行成功)
希望可以收到您的回复,谢谢

**Comment by Sinchuck** [comment]
我弄好了,不好意思
