### ISSUE TITLE
为什么我pip安装都有问题

### ISSUE THREAD

**Issue by huangrs494** [2shou/TextGrocery#26]
pip提示安装成功了，但是import tgrocery，报错如下，哪位大神能解释一下
python3版本的问题：
    from converter import *
ImportError: No module named 'converter'

python2版本的问题：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda2\lib\site-packages\tgrocery\__init__.py", line 2, in <module>
    from classifier import *
  File "D:\anaconda2\lib\site-packages\tgrocery\classifier.py", line 6, in <module>
    from .learner import *
  File "D:\anaconda2\lib\site-packages\tgrocery\learner\__init__.py", line 1, in <module>
    from .learner import *
  File "D:\anaconda2\lib\site-packages\tgrocery\learner\learner.py", line 21, in <module>
    util = CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'util.so.1'))
  File "D:\anaconda2\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]

**Comment by MobileAppVault** [comment]
use python2.7 and install converter with `pip install converter`

**Comment by loike** [comment]
请问这个问题解决了吗，我在python2.7下pip install converter之后import tgrocery还是报同样的错误

**Comment by 2shou** [comment]
仍然不能支持Windows，请尝试Linux或Mac
