### ISSUE TITLE
Not running in Debian

### ISSUE THREAD

**Issue by MilesOkeefe** [2shou/TextGrocery#3]
I used this library successfully in OS X (10.10.3) but when I try to run the same code on my Debian (wheezy) system, it fails with this error:

  
	Traceback (most recent call last):
		File "generate_classifications.py", line 4, in <module>
			from tgrocery import Grocery
		File "/usr/local/lib/python2.7/dist-packages/tgrocery/__init__.py", line 2, in <module>
			from classifier import *
		File "/usr/local/lib/python2.7/dist-packages/tgrocery/classifier.py", line 6, in <module>
			from .learner import *
		File "/usr/local/lib/python2.7/dist-packages/tgrocery/learner/__init__.py", line 1, in <module>
			from .learner import *
		File "/usr/local/lib/python2.7/dist-packages/tgrocery/learner/learner.py", line 26, in <module>
			import liblinear
		File "/usr/local/lib/python2.7/dist-packages/tgrocery/learner/liblinear/python/liblinear.py", line 9, in <module>
			liblinear = CDLL(path.join(path.dirname(path.abspath(__file__)), '../liblinear.so.1'))
		File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
			self._handle = _dlopen(self._name, mode)
	OSError: /usr/local/lib/python2.7/dist-packages/tgrocery/learner/liblinear/python/../liblinear.so.1: cannot open shared object file: No such file or directory

More details:

- `/usr/local/lib` is in my path.
- OSX is running python 2.7.6, Debian is running python 2.7.3

Any idea why this might be happening?

**Comment by 2shou** [comment]
I believe this is due to lack of C compile environment for your Debian system.
Please try the following command under sudo permission:
```
apt-get install gcc make g++ -y
```

**Comment by MilesOkeefe** [comment]
@2shou hm, looks like all of those packages are already installed and up to date.

I ended up just copying the missing file, `liblinear.so.1` into the python package directory. It's super hacky, but it worked for me:

	cp ./TextGrocery/tgrocery/learner/liblinear/liblinear.so.1 /usr/local/lib/python2.7/dist-packages/tgrocery/learner/liblinear/python/../liblinear.so.1

**Comment by 2shou** [comment]
I tried to install `TextGrocery` under `Debian 7.8` and `Python 2.7.3`, using `pip install tgrocery` command. And It worked finally, after C compile environment configuration.
So I wonder if you could tell me what wrong is.
